### ISSUE TITLE
ImportError: cannot import name 'tukey' from 'scipy.signal'

### ISSUE THREAD

**Issue by juvenalandres** [xtyangpsp/SeisGo#29]
Hello,

I've just installed Seisgo and when checking the installation per the instructions I get the following error,

```

>>> from seisgo import obsmaster as obs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\j.andres\Anaconda3\envs\seisgo\SeisGo\seisgo\obsmaster.py", line 4, in <module>
    from seisgo import utils,downloaders
  File "C:\Users\j.andres\Anaconda3\envs\seisgo\SeisGo\seisgo\utils.py", line 14, in <module>
    from scipy.signal import tukey,hilbert
ImportError: cannot import name 'tukey' from 'scipy.signal' (C:\Users\j.andres\Anaconda3\envs\seisgo\Lib\site-packages\scipy\signal\__init__.py)
```

Searching Scipy documentation, seems that `tukey` is not withing `scipy.signal` but `scipy.signal.windows.tukey`.

Is that correct? If not, could you suggest any insight on the problem?

Thank you.

**Comment by xtyangpsp** [comment]
I figured it is a version issue. In oder versions (i.e., 1.7.3 on my computer), tukey exists in both scipy.signal and scipy.signal.windows. However, it seems in the latest version (1.13.x), tukey only exists in scipy.signal.windows. I have updated the code to be import it from the windows module. Thanks for using SeisGo and report the bug. You can run `git pull` and rerun `pip install .` in the SeisGo folder, the issue should be resolved.
