### ISSUE TITLE
cannot import name 'tukey' from 'scipy.signal'

### ISSUE THREAD

**Issue by RunningXinLiu** [xtyangpsp/SeisGo#30]
HI Prof. Yang,

I finally managed to install seisgo and there is a problem that I encountered and I want share in this issure, and I think it might help others to quickly fix their problem.

The automatically downloaded scipy version is 1.13.0 and I kept recieving the error "cannot import name 'tukey' from 'scipy.signal". However, after I downgrade scipy to 1.10.1, there is no problem with it.

So I think there is a version dependency on scipy too and maybe you could mention this in your tutorial.

Cheers,
Xin

**Comment by xtyangpsp** [comment]
Thanks for the note. Did you install the pip release or the version on GitHub? I thought I have addressed this in the GitHub version but haven’t released it yet. On Apr 19, 2024, at 11:42 PM, XIN LIU ***@***.***> wrote:﻿
HI Prof. Yang,
I finally managed to install seisgo and there is a problem that I encountered and I want share in this issure, and I think it might help others to quickly fix their problem.
The automatically downloaded scipy version is 1.13.0 and I kept recieving the error "cannot import name 'tukey' from 'scipy.signal". However, after I downgrade scipy to 1.10.1, there is no problem with it.
So I think there is a version dependency on scipy too and maybe you could mention this in your tutorial.
Cheers,
Xin

**Comment by xtyangpsp** [comment]
I checked and found that I only fixed the one in utils but not the one in obsmaster. Thanks again for the note. I am fixing them all and getting them ready for a new release on pip.

**Comment by RunningXinLiu** [comment]
No, due to the VPN problem, I can not do pip install nor the git clone from the repo... I download the zip file and install it with pip install ./

**Comment by xtyangpsp** [comment]
Why is there a VPN issue? pip projects and GitHub are all open source codes. Can you describe the issue? BTW, I have created a new release with the tukey issue fixed.

**Comment by RunningXinLiu** [comment]
I am not very sure about how this works. GitHub is actually banned in mainland China. And I cannot git clone nor pip install directly from your repo (the mirrored channel i am using is the USTC mirror). The only way for me is to download the zip file from GitHub and install it locally.

**Comment by xtyangpsp** [comment]
That is sadly surprising! Thanks for the information.
